IPaidThat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bill/', include("bill.urls")),
]

bill/urls.py
from . import views
from django.urls import path
from django.conf.urls import url
from django.urls import path, include # new

app_name = 'bill'
urlpatterns = [
    path('login/', views.login, name='login'),
]

bill/models.py
from django.db import models

# Create your models here.
from django.db import models


class RetObject(models.Model):
    email = models.CharField(max_length=200)
    invoice_number = models.CharField(max_length=100)
    date = models.DateTimeField()
    client_name = models.CharField(max_length=200)
    total_ttc = models.CharField(max_length=50)
    total_vat = models.TextField(max_length=50)

bill/forms.py
from django import forms


class LoginForm(forms.Form):

    def get_email(self):
        return self.email

    def get_password(self):
        return self.password

    email = forms.CharField(max_length=300)
    password = forms.CharField(widget=forms.PasswordInput())

bill/views.py
from django.shortcuts import render
from bill.forms import *
from .models import RetObject
from .utils import back

# Create your views here.


# THE VIEW
def login(request):
    if request.method == 'POST':
        MyForms = LoginForm(request.POST)
        if MyForms.is_valid():
            back(MyForms.data.get("email"), MyForms.data.get("password"))
            # GET ALL OBJECT OF THE RIGHT EMAIL
            bills_list = RetObject.objects.filter(email=MyForms.data.get("email"))
            context = {'bills_list': bills_list}
            if not bills_list:
                return render(request, 'login.html', {"form": MyForms, "error": "error"})
            return render(request, 'loggedin.html', context)
    else:
        MyForms = LoginForm()
    return render(request, 'login.html', {"form": MyForms})

bill/templates/loggedin.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<body class="bg-dark text-white">
<div class="container">
{% if bills_list %}
    {% for el in bills_list %}
        <li class="list-group-item list-group-item-action">
        <ul>
            <li class="list-group-item list-group-item-dark">{{ el.invoice_number }}</li>
            <li class="list-group-item list-group-item-dark">{{ el.date }}</li>
            <li class="list-group-item list-group-item-dark">{{ el.client_name }}</li>
            <li class="list-group-item list-group-item-dark">{{ el.total_ttc }}</li>
            <li class="list-group-item list-group-item-dark">{{ el.total_vat }}</li>
        </ul>
        </li>
    {% endfor %}
{% else %}
    <p class="p-0">Nothing to show.</p>
{% endif %}
</div>
</body>

bill/templates/login.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<!-- templates/registration/login.html -->
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body class="bg-dark text-white">
<div class="container" style="">
    <div class="h-25"></div>
        <h1 class="text-center">Login</h1>
    <br>
    <div class="text-center">
    <form method="post" action="{% url 'bill:login' %}">
        <div class="form-group">
        {% csrf_token %}
        {{ form.as_p }}
        </div>
        {% if error == "error" %}
            <p>Try with an other mail or password</p>
        {%  endif %}
        <button type="submit" class="btn btn-info ">Login</button>
    </form>
        </div>
</div>
</body>